name: Build and Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ed15356631561/helloworld

    - name: Request code review
      uses: reviewdog/action-setup@v1
      with:
        tool_name: "eslint"
        reporter: "github-pr-review"
        github_token: ${{ secrets.REVIEW_TOKEN }}
        level: "warning"
        filter_mode: "diff_context"
        reviewer1: "zhengjianfeng1103"
        reviewer2: "mangosteenLi"
        reviewer3: "China-Chris"
        require_changes_approved: 1
        approval_count: 2
      if: github.ref == 'refs/heads/develop'
