// Code generated by goctl. DO NOT EDIT.

package cache

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	invitationTreesFieldNames          = builder.RawFieldNames(&InvitationTrees{})
	invitationTreesRows                = strings.Join(invitationTreesFieldNames, ",")
	invitationTreesRowsExpectAutoSet   = strings.Join(stringx.Remove(invitationTreesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	invitationTreesRowsWithPlaceHolder = strings.Join(stringx.Remove(invitationTreesFieldNames, "`invitationTreeId`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	invitationTreesModel interface {
		Insert(ctx context.Context, data *InvitationTrees) (sql.Result, error)
		FindOne(ctx context.Context, invitationTreeId int64) (*InvitationTrees, error)
		Update(ctx context.Context, data *InvitationTrees) error
		Delete(ctx context.Context, invitationTreeId int64) error
	}

	defaultInvitationTreesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InvitationTrees struct {
		InvitationTreeId int64        `db:"invitationTreeId"`
		CreatedAt        time.Time    `db:"created_at"`
		UpdatedAt        time.Time    `db:"updated_at"`
		DeletedAt        sql.NullTime `db:"deleted_at"`
		UserId           int64        `db:"userId"`
		ParentId         int64        `db:"parentId"`
		Depth            int64        `db:"depth"`
	}
)

func newInvitationTreesModel(conn sqlx.SqlConn) *defaultInvitationTreesModel {
	return &defaultInvitationTreesModel{
		conn:  conn,
		table: "`invitation_trees`",
	}
}

func (m *defaultInvitationTreesModel) Delete(ctx context.Context, invitationTreeId int64) error {
	query := fmt.Sprintf("delete from %s where `invitationTreeId` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, invitationTreeId)
	return err
}

func (m *defaultInvitationTreesModel) FindOne(ctx context.Context, invitationTreeId int64) (*InvitationTrees, error) {
	query := fmt.Sprintf("select %s from %s where `invitationTreeId` = ? limit 1", invitationTreesRows, m.table)
	var resp InvitationTrees
	err := m.conn.QueryRowCtx(ctx, &resp, query, invitationTreeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInvitationTreesModel) Insert(ctx context.Context, data *InvitationTrees) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, invitationTreesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.InvitationTreeId, data.DeletedAt, data.UserId, data.ParentId, data.Depth)
	return ret, err
}

func (m *defaultInvitationTreesModel) Update(ctx context.Context, data *InvitationTrees) error {
	query := fmt.Sprintf("update %s set %s where `invitationTreeId` = ?", m.table, invitationTreesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.ParentId, data.Depth, data.InvitationTreeId)
	return err
}

func (m *defaultInvitationTreesModel) tableName() string {
	return m.table
}
