name: Sync Develop to Release

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:  # 手动触发器

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git Identity
        run: |
          git config user.email "edchiris@gmail.com"
          git config user.name "Ed"

      - name: Fetch All Branches
        run: git fetch --all

      - name: Sync Branches
        run: |
          git checkout release
          git pull origin release
          git merge --allow-unrelated-histories -X theirs develop
          git commit -am "Merge develop into release"
          git push origin release
