// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAdminRequest                       = user.AddAdminRequest
	AddAdminResponse                      = user.AddAdminResponse
	AddBlackListRequest                   = user.AddBlackListRequest
	AddBlackListResponse                  = user.AddBlackListResponse
	AddUserInfoRequest                    = user.AddUserInfoRequest
	AddUserInfoResponse                   = user.AddUserInfoResponse
	AdminLoginRequest                     = user.AdminLoginRequest
	AdminLoginResponse                    = user.AdminLoginResponse
	CheckTodayInviteRequest               = user.CheckTodayInviteRequest
	CheckTodayInviteResponse              = user.CheckTodayInviteResponse
	CheckTwitterIdRequest                 = user.CheckTwitterIdRequest
	CheckTwitterIdResponse                = user.CheckTwitterIdResponse
	CreateHelpCategoryRequest             = user.CreateHelpCategoryRequest
	CreateHelpCategoryResponse            = user.CreateHelpCategoryResponse
	CreateHelpCategoryTranslationRequest  = user.CreateHelpCategoryTranslationRequest
	CreateHelpCategoryTranslationResponse = user.CreateHelpCategoryTranslationResponse
	CreateInviteRequest                   = user.CreateInviteRequest
	CreateInviteResponse                  = user.CreateInviteResponse
	CreateUserRequest                     = user.CreateUserRequest
	CreateUserResponse                    = user.CreateUserResponse
	DeleteHelpCategoryRequest             = user.DeleteHelpCategoryRequest
	DeleteHelpCategoryResponse            = user.DeleteHelpCategoryResponse
	DeleteHelpCategoryTranslationRequest  = user.DeleteHelpCategoryTranslationRequest
	DeleteHelpCategoryTranslationResponse = user.DeleteHelpCategoryTranslationResponse
	EditHelpCategoryRequest               = user.EditHelpCategoryRequest
	EditHelpCategoryResponse              = user.EditHelpCategoryResponse
	GetHelpCategoriesRequest              = user.GetHelpCategoriesRequest
	GetHelpCategoriesResponse             = user.GetHelpCategoriesResponse
	GetHelpCategoryTranslationsRequest    = user.GetHelpCategoryTranslationsRequest
	GetHelpCategoryTranslationsResponse   = user.GetHelpCategoryTranslationsResponse
	HelpCategory                          = user.HelpCategory
	HelpCategoryTranslation               = user.HelpCategoryTranslation
	QueryBlackListRequest                 = user.QueryBlackListRequest
	QueryBlackListResponse                = user.QueryBlackListResponse
	QueryUserRequest                      = user.QueryUserRequest
	QueryUserResponse                     = user.QueryUserResponse
	RemoveAdminRequest                    = user.RemoveAdminRequest
	RemoveAdminResponse                   = user.RemoveAdminResponse
	RemoveBlackListRequest                = user.RemoveBlackListRequest
	RemoveBlackListResponse               = user.RemoveBlackListResponse
	Request                               = user.Request
	Response                              = user.Response

	User interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		CheckTwitterId(ctx context.Context, in *CheckTwitterIdRequest, opts ...grpc.CallOption) (*CheckTwitterIdResponse, error)
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
		CreateInvite(ctx context.Context, in *CreateInviteRequest, opts ...grpc.CallOption) (*CreateInviteResponse, error)
		CheckTodayInvite(ctx context.Context, in *CheckTodayInviteRequest, opts ...grpc.CallOption) (*CheckTodayInviteResponse, error)
		AddUserInfo(ctx context.Context, in *AddUserInfoRequest, opts ...grpc.CallOption) (*AddUserInfoResponse, error)
		QueryUser(ctx context.Context, in *QueryUserRequest, opts ...grpc.CallOption) (*QueryUserResponse, error)
		AddAdmin(ctx context.Context, in *AddAdminRequest, opts ...grpc.CallOption) (*AddAdminResponse, error)
		AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error)
		RemoveAdmin(ctx context.Context, in *RemoveAdminRequest, opts ...grpc.CallOption) (*RemoveAdminResponse, error)
		AddBlackList(ctx context.Context, in *AddBlackListRequest, opts ...grpc.CallOption) (*AddBlackListResponse, error)
		QueryBlackList(ctx context.Context, in *QueryBlackListRequest, opts ...grpc.CallOption) (*QueryBlackListResponse, error)
		RemoveBlackList(ctx context.Context, in *RemoveBlackListRequest, opts ...grpc.CallOption) (*RemoveBlackListResponse, error)
		GetHelpCategories(ctx context.Context, in *GetHelpCategoriesRequest, opts ...grpc.CallOption) (*GetHelpCategoriesResponse, error)
		CreateHelpCategory(ctx context.Context, in *CreateHelpCategoryRequest, opts ...grpc.CallOption) (*CreateHelpCategoryResponse, error)
		DeleteHelpCategory(ctx context.Context, in *DeleteHelpCategoryRequest, opts ...grpc.CallOption) (*DeleteHelpCategoryResponse, error)
		EditHelpCategory(ctx context.Context, in *EditHelpCategoryRequest, opts ...grpc.CallOption) (*EditHelpCategoryResponse, error)
		CreateHelpCategoryTranslation(ctx context.Context, in *CreateHelpCategoryTranslationRequest, opts ...grpc.CallOption) (*CreateHelpCategoryTranslationResponse, error)
		DeleteHelpCategoryTranslation(ctx context.Context, in *DeleteHelpCategoryTranslationRequest, opts ...grpc.CallOption) (*DeleteHelpCategoryTranslationResponse, error)
		GetHelpCategoryTranslations(ctx context.Context, in *GetHelpCategoryTranslationsRequest, opts ...grpc.CallOption) (*GetHelpCategoryTranslationsResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultUser) CheckTwitterId(ctx context.Context, in *CheckTwitterIdRequest, opts ...grpc.CallOption) (*CheckTwitterIdResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckTwitterId(ctx, in, opts...)
}

func (m *defaultUser) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUser) CreateInvite(ctx context.Context, in *CreateInviteRequest, opts ...grpc.CallOption) (*CreateInviteResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateInvite(ctx, in, opts...)
}

func (m *defaultUser) CheckTodayInvite(ctx context.Context, in *CheckTodayInviteRequest, opts ...grpc.CallOption) (*CheckTodayInviteResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckTodayInvite(ctx, in, opts...)
}

func (m *defaultUser) AddUserInfo(ctx context.Context, in *AddUserInfoRequest, opts ...grpc.CallOption) (*AddUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddUserInfo(ctx, in, opts...)
}

func (m *defaultUser) QueryUser(ctx context.Context, in *QueryUserRequest, opts ...grpc.CallOption) (*QueryUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.QueryUser(ctx, in, opts...)
}

func (m *defaultUser) AddAdmin(ctx context.Context, in *AddAdminRequest, opts ...grpc.CallOption) (*AddAdminResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddAdmin(ctx, in, opts...)
}

func (m *defaultUser) AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AdminLogin(ctx, in, opts...)
}

func (m *defaultUser) RemoveAdmin(ctx context.Context, in *RemoveAdminRequest, opts ...grpc.CallOption) (*RemoveAdminResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RemoveAdmin(ctx, in, opts...)
}

func (m *defaultUser) AddBlackList(ctx context.Context, in *AddBlackListRequest, opts ...grpc.CallOption) (*AddBlackListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddBlackList(ctx, in, opts...)
}

func (m *defaultUser) QueryBlackList(ctx context.Context, in *QueryBlackListRequest, opts ...grpc.CallOption) (*QueryBlackListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.QueryBlackList(ctx, in, opts...)
}

func (m *defaultUser) RemoveBlackList(ctx context.Context, in *RemoveBlackListRequest, opts ...grpc.CallOption) (*RemoveBlackListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RemoveBlackList(ctx, in, opts...)
}

func (m *defaultUser) GetHelpCategories(ctx context.Context, in *GetHelpCategoriesRequest, opts ...grpc.CallOption) (*GetHelpCategoriesResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetHelpCategories(ctx, in, opts...)
}

func (m *defaultUser) CreateHelpCategory(ctx context.Context, in *CreateHelpCategoryRequest, opts ...grpc.CallOption) (*CreateHelpCategoryResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateHelpCategory(ctx, in, opts...)
}

func (m *defaultUser) DeleteHelpCategory(ctx context.Context, in *DeleteHelpCategoryRequest, opts ...grpc.CallOption) (*DeleteHelpCategoryResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteHelpCategory(ctx, in, opts...)
}

func (m *defaultUser) EditHelpCategory(ctx context.Context, in *EditHelpCategoryRequest, opts ...grpc.CallOption) (*EditHelpCategoryResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.EditHelpCategory(ctx, in, opts...)
}

func (m *defaultUser) CreateHelpCategoryTranslation(ctx context.Context, in *CreateHelpCategoryTranslationRequest, opts ...grpc.CallOption) (*CreateHelpCategoryTranslationResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateHelpCategoryTranslation(ctx, in, opts...)
}

func (m *defaultUser) DeleteHelpCategoryTranslation(ctx context.Context, in *DeleteHelpCategoryTranslationRequest, opts ...grpc.CallOption) (*DeleteHelpCategoryTranslationResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteHelpCategoryTranslation(ctx, in, opts...)
}

func (m *defaultUser) GetHelpCategoryTranslations(ctx context.Context, in *GetHelpCategoryTranslationsRequest, opts ...grpc.CallOption) (*GetHelpCategoryTranslationsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetHelpCategoryTranslations(ctx, in, opts...)
}
